apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: reproducible-build-run-2-
  labels:
    app.kubernetes.io/part-of: reproducible-build-demo
    demo/run: "2"
spec:
  pipelineRef:
    name: reproducible-build
  params:
    - name: git-url
      value: "https://github.com/cloud-talks/reproducible-builds"
    - name: git-revision
      value: "29859cf05450f211368294fda9b88acb21be5c67"
    - name: image
      value: "ttl.sh/reproducible-demo-oss-mumbai"
    - name: build-extra-args
      value: "--source-date-epoch 0 --rewrite-timestamp"
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
