#!/usr/bin/env bash
#
# Runs the full reproducible builds demonstration:
#
#   1. Builds the same Dockerfile twice without reproducibility flags
#   2. Shows the source code and Dockerfile
#   3. Rebuilds with --source-date-epoch 0 --rewrite-timestamp
#   4. Verifies SLSA provenance generated by Tekton Chains
#   5. Runs a policy gate check on the provenance
#   6. Demonstrates hermetic execution (no network access)
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "${SCRIPT_DIR}")"

DRY_RUN="${DRY_RUN:-false}"

# ── Helpers ────────────────────────────────────────────────────────
BOLD='\033[1m'
GREEN='\033[0;32m'
RED='\033[0;31m'
CYAN='\033[0;36m'
YELLOW='\033[0;33m'
RESET='\033[0m'

banner() {
  echo ""
  echo -e "${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
  echo -e "${BOLD}${CYAN}  $*${RESET}"
  echo -e "${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
  echo ""
}
info()   { echo -e "${BOLD}$*${RESET}"; }
pass()   { echo -e "${GREEN}${BOLD}✓ $*${RESET}"; }
fail()   { echo -e "${RED}${BOLD}✗ $*${RESET}"; }
warn()   { echo -e "${YELLOW}${BOLD}⚠ $*${RESET}"; }

wait_for_pipelinerun() {
  local name="$1"
  local timeout="${2:-300}"
  info "Waiting for PipelineRun ${name} to complete (timeout: ${timeout}s)..."

  if ! kubectl wait --for=condition=Succeeded --timeout="${timeout}s" \
    "pipelinerun/${name}" 2>/dev/null; then
    local status
    status=$(kubectl get pipelinerun "${name}" -o jsonpath='{.status.conditions[0].status}')
    if [ "${status}" = "False" ]; then
      fail "PipelineRun ${name} FAILED"
      kubectl get pipelinerun "${name}" -o jsonpath='{.status.conditions[0].message}'
      echo ""
      return 1
    fi
    fail "PipelineRun ${name} timed out"
    return 1
  fi
  pass "PipelineRun ${name} succeeded"
}

get_result() {
  local run="$1" result="$2"
  kubectl get pipelinerun "${run}" \
    -o jsonpath="{.status.results[?(@.name==\"${result}\")].value}"
}

# ── Dry-run mode ──────────────────────────────────────────────────
if [ "${DRY_RUN}" = "true" ]; then
  warn "DRY-RUN MODE — showing simulated output (no cluster required)"
  echo ""

  NAIVE_DIGEST_1="sha256:aaa111bbb222ccc333ddd444eee555fff666aaa111bbb222ccc333ddd444eee555"
  NAIVE_DIGEST_2="sha256:999888777666555444333222111000fff999888777666555444333222111000eee"
  REPRO_DIGEST="sha256:75d4b60a847dba85446f05b676a0d0172faeff3ade8005c91d979ffe7d16b446"

  banner "Building the same Dockerfile twice"
  info "Same source code, same commit, same build tool — no reproducibility flags."
  sleep 1
  pass "Build #1 succeeded"
  pass "Build #2 succeeded"
  echo ""
  info "Build #1:  ${NAIVE_DIGEST_1}"
  info "Build #2:  ${NAIVE_DIGEST_2}"
  echo ""
  fail "DIGESTS DO NOT MATCH — same Dockerfile, different images!"
  echo ""
  echo "  Buildah embedded real timestamps → different image config → different digest."
  echo ""
  read -rp "Press Enter to continue..."

  banner "Now with reproducibility flags"
  info "Same Dockerfile — adding: buildah --source-date-epoch 0 --rewrite-timestamp"
  sleep 2
  pass "Build #1 succeeded"
  pass "Build #2 succeeded"
  echo ""
  info "Build #1:  ${REPRO_DIGEST}"
  info "Build #2:  ${REPRO_DIGEST}"
  echo ""
  pass "DIGESTS MATCH — builds are byte-identical!"
  echo ""
  read -rp "Press Enter to continue..."

  banner "SLSA Provenance via Tekton Chains"
  pass "Signed by Tekton Chains"
  pass "SLSA provenance decoded"
  pass "DSSE envelope inspected"
  pass "Cosign signature verified"
  echo ""
  read -rp "Press Enter to continue..."

  banner "Policy Gate — Should this image be deployed?"
  echo -e "  ${GREEN}${BOLD}  ██ ALLOW — deploy permitted${RESET}"
  echo ""
  read -rp "Press Enter to continue..."

  banner "Hermetic Execution — No Network Access"
  pass "Network access blocked — hermetic mode working"
  echo ""

  banner "What We Proved"
  echo "  1. Without reproducibility flags → same code, different images"
  echo "  2. With two buildah flags         → same code, identical images"
  echo "  3. Tekton Chains                  → automatic signed SLSA provenance"
  echo "  4. Policy gate                    → provenance verified before deploy"
  echo "  5. Hermetic execution             → no network access during build"
  echo ""
  warn "DRY-RUN MODE — simulated output, no cluster was used"
  exit 0
fi

# ══════════════════════════════════════════════════════════════════

# ── Two builds, same Dockerfile ──────────────────────────────────
banner "Building the same Dockerfile twice"

info "Same source code, same commit, same build tool — let's see what happens."
echo ""

NAIVE1_NAME=$(kubectl create -f "${PROJECT_DIR}/tekton/runs/run-naive-1.yaml" -o name | sed 's|pipelinerun.tekton.dev/||')
echo "  → ${NAIVE1_NAME}"
NAIVE2_NAME=$(kubectl create -f "${PROJECT_DIR}/tekton/runs/run-naive-2.yaml" -o name | sed 's|pipelinerun.tekton.dev/||')
echo "  → ${NAIVE2_NAME}"

echo ""
wait_for_pipelinerun "${NAIVE1_NAME}" 600
wait_for_pipelinerun "${NAIVE2_NAME}" 600

NAIVE_DIGEST1=$(get_result "${NAIVE1_NAME}" "IMAGE_DIGEST")
NAIVE_DIGEST2=$(get_result "${NAIVE2_NAME}" "IMAGE_DIGEST")

echo ""
info "Build #1 (no flags):  ${NAIVE_DIGEST1}"
info "Build #2 (no flags):  ${NAIVE_DIGEST2}"
echo ""

if [ "${NAIVE_DIGEST1}" != "${NAIVE_DIGEST2}" ]; then
  fail "DIGESTS DO NOT MATCH — same Dockerfile, different images!"
  echo ""
  echo "  Same source, same Dockerfile, same commit."
  echo "  Buildah embedded real timestamps → different image config → different digest."
else
  warn "Digests unexpectedly match — buildah may have cached layers."
fi

echo ""
read -rp "Press Enter to continue..."

# ── Source code + Dockerfile ─────────────────────────────────────
banner "The Source Code"

info "Go application (demo-app/main.go):"
echo "---"
cat "${PROJECT_DIR}/demo-app/main.go"
echo "---"
echo ""

info "Dockerfile (demo-app/Dockerfile):"
echo "---"
cat "${PROJECT_DIR}/demo-app/Dockerfile"
echo "---"
echo ""
read -rp "Press Enter to continue..."

# ── Reproducible builds ──────────────────────────────────────────
banner "Now with reproducibility flags"

info "Same Dockerfile, same commit — adding: buildah --source-date-epoch 0 --rewrite-timestamp"
echo ""

RUN1_NAME=$(kubectl create -f "${PROJECT_DIR}/tekton/runs/run-1.yaml" -o name | sed 's|pipelinerun.tekton.dev/||')
echo "  → ${RUN1_NAME}"
RUN2_NAME=$(kubectl create -f "${PROJECT_DIR}/tekton/runs/run-2.yaml" -o name | sed 's|pipelinerun.tekton.dev/||')
echo "  → ${RUN2_NAME}"

echo ""
info "Both PipelineRuns executing in parallel..."
echo ""

wait_for_pipelinerun "${RUN1_NAME}" 600
wait_for_pipelinerun "${RUN2_NAME}" 600

# ── Compare digests ──────────────────────────────────────────────
DIGEST1=$(get_result "${RUN1_NAME}" "IMAGE_DIGEST")
DIGEST2=$(get_result "${RUN2_NAME}" "IMAGE_DIGEST")

echo ""
info "Build #1 (with flags):  ${DIGEST1}"
info "Build #2 (with flags):  ${DIGEST2}"
echo ""

if [ "${DIGEST1}" = "${DIGEST2}" ]; then
  pass "DIGESTS MATCH — builds are byte-identical!"
  echo ""
  echo "  Without flags:  different timestamps → different digests"
  echo "  With flags:     timestamps zeroed   → identical digests"
  echo ""
else
  fail "DIGESTS DO NOT MATCH — investigate build logs"
fi

read -rp "Press Enter to continue..."

# ── Provenance ───────────────────────────────────────────────────
banner "SLSA Provenance via Tekton Chains"

info "Checking if Chains has signed PipelineRun #1..."
echo ""

MAX_WAIT=60
WAITED=0
while [ ${WAITED} -lt ${MAX_WAIT} ]; do
  SIGNED=$(kubectl get pipelinerun "${RUN1_NAME}" \
    -o jsonpath='{.metadata.annotations.chains\.tekton\.dev/signed}' 2>/dev/null || true)
  if [ "${SIGNED}" = "true" ]; then
    break
  fi
  echo "  Waiting for Chains to sign (${WAITED}s / ${MAX_WAIT}s)..."
  sleep 5
  WAITED=$((WAITED + 5))
done

if [ "${SIGNED}" = "true" ]; then
  pass "PipelineRun #1 is signed by Tekton Chains"
else
  fail "Chains did not sign within ${MAX_WAIT}s — check chains controller logs"
  echo "  kubectl logs -n tekton-chains -l app=tekton-chains-controller"
fi

RUN1_UID=$(kubectl get pipelinerun "${RUN1_NAME}" -o jsonpath='{.metadata.uid}')

# ── 4a: Where the attestation lives ──────────────────────────────
echo ""
info "Where Chains stores the attestation:"
echo ""
kubectl get pipelinerun "${RUN1_NAME}" -o json | python3 -c "
import sys, json
annots = json.load(sys.stdin)['metadata'].get('annotations', {})
for k in sorted(annots):
    if 'chains' in k:
        print(f'  {k} ({len(annots[k])} chars)')
"
echo ""

# ── 4b: SLSA provenance payload ─────────────────────────────────
info "Decoding SLSA provenance payload..."
echo ""

PAYLOAD=$(kubectl get pipelinerun "${RUN1_NAME}" \
  -o jsonpath="{.metadata.annotations.chains\.tekton\.dev/payload-pipelinerun-${RUN1_UID}}" \
  2>/dev/null || true)

if [ -n "${PAYLOAD}" ]; then
  echo "${PAYLOAD}" | base64 -d | python3 -m json.tool 2>/dev/null || \
    echo "${PAYLOAD}" | base64 -d
  echo ""
  pass "SLSA provenance retrieved and decoded"
else
  warn "Payload not stored as annotation (may be in OCI storage)."
fi

# ── 4c: DSSE envelope ───────────────────────────────────────────
echo ""
info "Inspecting the DSSE signature envelope..."
echo ""

kubectl get pipelinerun "${RUN1_NAME}" \
  -o jsonpath="{.metadata.annotations.chains\.tekton\.dev/signature-pipelinerun-${RUN1_UID}}" \
  | base64 -d | python3 -c "
import sys, json
env = json.load(sys.stdin)
print('DSSE Envelope:')
print(f'  payloadType: {env[\"payloadType\"]}')
print(f'  payload:     ({len(env[\"payload\"])} chars, base64-encoded provenance)')
print(f'  signatures:  {len(env[\"signatures\"])} signature(s)')
for i, sig in enumerate(env['signatures']):
    print(f'    [{i}] keyid: {sig.get(\"keyid\", \"(empty)\")}')
    print(f'        sig:   {sig[\"sig\"][:40]}...')
" 2>/dev/null || info "(Could not parse DSSE envelope)"

# ── 4d: Cosign verification ─────────────────────────────────────
echo ""
info "Verifying signature with cosign..."
echo ""

COSIGN_RESULT=$(cosign verify-blob-attestation \
  --insecure-ignore-tlog \
  --key k8s://tekton-chains/signing-secrets \
  --signature <(kubectl get pipelinerun "${RUN1_NAME}" \
    -o jsonpath="{.metadata.annotations.chains\.tekton\.dev/signature-pipelinerun-${RUN1_UID}}" | base64 -d) \
  --type slsaprovenance1 \
  --check-claims=false \
  /dev/null 2>&1 || true)

if echo "${COSIGN_RESULT}" | grep -qi "verified ok\|verified"; then
  pass "Signature verified with cosign"
else
  info "cosign output: ${COSIGN_RESULT}"
fi

read -rp "Press Enter to continue..."

# ── Policy gate ──────────────────────────────────────────────────
banner "Policy Gate — Should this image be deployed?"

info "Does this image have valid signed provenance?"
echo ""
"${SCRIPT_DIR}/policy-check.sh" "${RUN1_NAME}" || true

read -rp "Press Enter to continue..."

# ── Hermetic execution ───────────────────────────────────────────
banner "Hermetic Execution — No Network Access"

info "Running a TaskRun with network completely disabled."
echo ""

kubectl apply -f "${PROJECT_DIR}/tekton/tasks/verify-hermetic.yaml" 2>/dev/null
HERMETIC_NAME=$(kubectl create -f "${PROJECT_DIR}/tekton/runs/run-hermetic.yaml" -o name 2>/dev/null | sed 's|taskrun.tekton.dev/||') || true

if [ -n "${HERMETIC_NAME}" ]; then
  echo "  → ${HERMETIC_NAME}"
  echo ""
  if kubectl wait --for=condition=Succeeded --timeout=60s "taskrun/${HERMETIC_NAME}" 2>/dev/null; then
    pass "Hermetic TaskRun succeeded"
    echo ""
    kubectl logs "${HERMETIC_NAME}-pod" --container=step-verify-no-network 2>/dev/null || true
  else
    warn "Hermetic execution requires Docker (not Podman) as the container runtime."
    echo "  The TaskRun may have failed due to namespace isolation restrictions."
  fi
else
  warn "Could not create hermetic TaskRun. Requires alpha API fields enabled."
fi

# ── Recap ─────────────────────────────────────────────────────────
banner "What We Proved"

echo "  1. Without reproducibility flags → same code, different images"
echo "  2. With two buildah flags         → same code, identical images"
echo "  3. Tekton Chains                  → automatic signed SLSA provenance"
echo "  4. Policy gate                    → provenance verified before deploy"
echo "  5. Hermetic execution             → build runs with no network access"
echo ""
echo "Key ingredients:"
echo ""
echo "  Dockerfile:"
echo "  • Pinned base images by digest    → no base image drift"
echo "  • -trimpath -ldflags='-buildid='  → deterministic Go binary"
echo ""
echo "  Buildah:"
echo "  • --source-date-epoch 0           → zeroed timestamps"
echo "  • --rewrite-timestamp             → clamped file metadata"
echo ""
echo "  Tekton:"
echo "  • Parameterized PipelineRun       → explicit, repeatable inputs"
echo "  • Tekton Chains                   → automatic signed SLSA provenance"
echo "  • Hermetic execution       → no network access during build"
echo ""
echo "  provenance + reproducibility = verifiable supply chain"
echo ""
