#!/usr/bin/env bash
#
# Live demo script for "From Pipelines to Provenance"
#
# Executes two independent PipelineRuns of the same source, compares
# their image digests to prove reproducibility, and verifies SLSA
# provenance generated by Tekton Chains.
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "${SCRIPT_DIR}")"

# ── Helpers ────────────────────────────────────────────────────────
BOLD='\033[1m'
GREEN='\033[0;32m'
RED='\033[0;31m'
CYAN='\033[0;36m'
RESET='\033[0m'

banner() { echo -e "\n${BOLD}${CYAN}━━━ $* ━━━${RESET}\n"; }
info()   { echo -e "${BOLD}$*${RESET}"; }
pass()   { echo -e "${GREEN}✓ $*${RESET}"; }
fail()   { echo -e "${RED}✗ $*${RESET}"; }

wait_for_pipelinerun() {
  local name="$1"
  local timeout="${2:-300}"
  info "Waiting for PipelineRun ${name} to complete (timeout: ${timeout}s)..."

  if ! kubectl wait --for=condition=Succeeded --timeout="${timeout}s" \
    "pipelinerun/${name}" 2>/dev/null; then
    # Check if it failed rather than timed out
    local status
    status=$(kubectl get pipelinerun "${name}" -o jsonpath='{.status.conditions[0].status}')
    if [ "${status}" = "False" ]; then
      fail "PipelineRun ${name} FAILED"
      kubectl get pipelinerun "${name}" -o jsonpath='{.status.conditions[0].message}'
      echo ""
      return 1
    fi
    fail "PipelineRun ${name} timed out"
    return 1
  fi
  pass "PipelineRun ${name} succeeded"
}

get_result() {
  local run="$1" result="$2"
  kubectl get pipelinerun "${run}" \
    -o jsonpath="{.status.results[?(@.name==\"${result}\")].value}"
}

# ── Act 1: Show what we're building ───────────────────────────────
banner "ACT 1: The Source"

info "Go application (demo-app/main.go):"
echo "---"
cat "${PROJECT_DIR}/demo-app/main.go"
echo "---"
echo ""

info "ko reproducibility config (demo-app/.ko.yaml):"
echo "---"
cat "${PROJECT_DIR}/demo-app/.ko.yaml"
echo "---"
echo ""
read -rp "Press Enter to start the builds..."

# ── Act 2: Run two independent builds ────────────────────────────
banner "ACT 2: Two Independent Builds"

info "Starting PipelineRun #1..."
RUN1_NAME=$(kubectl create -f "${PROJECT_DIR}/tekton/runs/run-1.yaml" -o name | sed 's|pipelinerun.tekton.dev/||')
echo "  → ${RUN1_NAME}"

info "Starting PipelineRun #2..."
RUN2_NAME=$(kubectl create -f "${PROJECT_DIR}/tekton/runs/run-2.yaml" -o name | sed 's|pipelinerun.tekton.dev/||')
echo "  → ${RUN2_NAME}"

echo ""
info "Both PipelineRuns are executing in parallel..."
echo ""

wait_for_pipelinerun "${RUN1_NAME}" 600
wait_for_pipelinerun "${RUN2_NAME}" 600

# ── Act 3: The Money Shot — Compare Digests ──────────────────────
banner "ACT 3: Comparing Image Digests"

DIGEST1=$(get_result "${RUN1_NAME}" "IMAGE_DIGEST")
DIGEST2=$(get_result "${RUN2_NAME}" "IMAGE_DIGEST")
URL1=$(get_result "${RUN1_NAME}" "IMAGE_URL")
URL2=$(get_result "${RUN2_NAME}" "IMAGE_URL")

echo ""
info "PipelineRun #1:"
echo "  IMAGE_URL:    ${URL1}"
echo "  IMAGE_DIGEST: ${DIGEST1}"
echo ""
info "PipelineRun #2:"
echo "  IMAGE_URL:    ${URL2}"
echo "  IMAGE_DIGEST: ${DIGEST2}"
echo ""

if [ "${DIGEST1}" = "${DIGEST2}" ]; then
  echo ""
  pass "DIGESTS MATCH — builds are byte-identical!"
  echo ""
  echo "  Two independent pipeline runs, same source, same digest."
  echo "  This is a reproducible build."
  echo ""
else
  echo ""
  fail "DIGESTS DO NOT MATCH"
  echo ""
  echo "  Run 1: ${DIGEST1}"
  echo "  Run 2: ${DIGEST2}"
  echo ""
  echo "  Something introduced non-determinism. Investigate the build logs:"
  echo "    kubectl logs ${RUN1_NAME}-build-pod"
  echo "    kubectl logs ${RUN2_NAME}-build-pod"
  echo ""
fi

read -rp "Press Enter to check provenance..."

# ── Act 4: Verify SLSA Provenance ────────────────────────────────
banner "ACT 4: SLSA Provenance via Tekton Chains"

info "Checking if Chains has signed PipelineRun #1..."
echo ""

# Give Chains a moment to reconcile
MAX_WAIT=60
WAITED=0
while [ ${WAITED} -lt ${MAX_WAIT} ]; do
  SIGNED=$(kubectl get pipelinerun "${RUN1_NAME}" \
    -o jsonpath='{.metadata.annotations.chains\.tekton\.dev/signed}' 2>/dev/null || true)
  if [ "${SIGNED}" = "true" ]; then
    break
  fi
  echo "  Waiting for Chains to sign (${WAITED}s / ${MAX_WAIT}s)..."
  sleep 5
  WAITED=$((WAITED + 5))
done

if [ "${SIGNED}" = "true" ]; then
  pass "PipelineRun #1 is signed by Tekton Chains"
else
  fail "Chains did not sign within ${MAX_WAIT}s — check chains controller logs"
  echo "  kubectl logs -n tekton-chains -l app=tekton-chains-controller"
fi

echo ""
info "Retrieving SLSA provenance payload..."
echo ""

RUN1_UID=$(kubectl get pipelinerun "${RUN1_NAME}" -o jsonpath='{.metadata.uid}')
PAYLOAD=$(kubectl get pipelinerun "${RUN1_NAME}" \
  -o jsonpath="{.metadata.annotations.chains\.tekton\.dev/payload-pipelinerun-${RUN1_UID}}" \
  2>/dev/null || true)

if [ -n "${PAYLOAD}" ]; then
  echo "${PAYLOAD}" | base64 -d | python3 -m json.tool 2>/dev/null || \
    echo "${PAYLOAD}" | base64 -d
  echo ""
  pass "SLSA provenance retrieved and decoded"
else
  info "Payload not stored as annotation (may be in OCI storage)."
  info "Checking signature annotation..."
  kubectl get pipelinerun "${RUN1_NAME}" \
    -o jsonpath='{.metadata.annotations}' | python3 -m json.tool 2>/dev/null | \
    grep -E "chains.tekton.dev" || true
fi

echo ""
info "Verifying signature with cosign..."
echo ""

COSIGN_RESULT=$(cosign verify-blob-attestation \
  --insecure-ignore-tlog \
  --key k8s://tekton-chains/signing-secrets \
  --signature <(kubectl get pipelinerun "${RUN1_NAME}" \
    -o jsonpath="{.metadata.annotations.chains\.tekton\.dev/signature-pipelinerun-${RUN1_UID}}" | base64 -d) \
  --type slsaprovenance \
  --check-claims=false \
  /dev/null 2>&1 || true)

if echo "${COSIGN_RESULT}" | grep -qi "verified ok\|verified"; then
  pass "Signature verified with cosign"
else
  info "cosign output: ${COSIGN_RESULT}"
  info "(Verification format may vary by cosign version — check manually if needed)"
fi

# ── Summary ──────────────────────────────────────────────────────
banner "SUMMARY"

echo "What we demonstrated:"
echo ""
echo "  1. Two independent PipelineRuns built from the same source"
echo "  2. Both produced byte-identical container images (same digest)"
echo "  3. Tekton Chains automatically generated SLSA provenance"
echo "  4. The provenance is cryptographically signed and verifiable"
echo ""
echo "Key ingredients for reproducibility:"
echo ""
echo "  • SOURCE_DATE_EPOCH=0      → no timestamp non-determinism"
echo "  • -trimpath                 → no filesystem path leakage"
echo "  • -ldflags='-buildid='     → no Go build ID variation"
echo "  • -ldflags='-s -w'         → stripped debug info"
echo "  • Pinned base image digest → no base image drift"
echo "  • Pinned git commit SHA    → no source code drift"
echo ""
echo "  provenance + reproducibility = verifiable supply chain"
echo ""
